version: '1.0'

services:

  postgres:
    image: postgres:11.13
    container_name: order-service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pizza_orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000